### Sign Up
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "username": "ahmedyousry",
    "email": "ahmedyou1@gmail.com",
    "password": "Ahmed@123"
}

### Log In
POST http://localhost:5000/auth/login
content-type: application/json

{
    "email": "ahmedyou@gmail.com",
    "password": "Ahmed@123"
}